export const projects = [
  {
    name: "Luxury Apartments",
    description: "Modern and luxurious apartments with stunning views",
    city: "Metropolis",
    no_of_bedrooms: 3,
    type: "Apartment",
  },
  {
    name: "Suburban House",
    description: "Spacious house with a large backyard in a quiet neighborhood",
    city: "Suburbville",
    no_of_bedrooms: 4,
    type: "House",
  },
  {
    name: "Downtown Condo",
    description: "Chic condo in the heart of the city with access to amenities",
    city: "Downtown City",
    no_of_bedrooms: 2,
    type: "Condo",
  },
  {
    name: "Cozy Cottage",
    description: "Quaint cottage with rustic charm and beautiful garden",
    city: "Countryside",
    no_of_bedrooms: 2,
    type: "Cottage",
  },
  {
    name: "Lakefront Villa",
    description: "Elegant villa with private access to a scenic lake",
    city: "Lakeside Town",
    no_of_bedrooms: 5,
    type: "Villa",
  },
  {
    name: "Urban Loft",
    description: "Trendy loft space in a bustling urban environment",
    city: "City Center",
    no_of_bedrooms: 1,
    type: "Loft",
  },
  {
    name: "Mountain Retreat",
    description:
      "Secluded retreat nestled in the mountains for ultimate relaxation",
    city: "Mountain Valley",
    no_of_bedrooms: 3,
    type: "Retreat",
  },
  {
    name: "Beachfront Bungalow",
    description: "Charming bungalow steps away from the sandy beach",
    city: "Coastal Paradise",
    no_of_bedrooms: 2,
    type: "Bungalow",
  },
  {
    name: "Golf Course Estate",
    description: "Stately estate overlooking a prestigious golf course",
    city: "Golfville",
    no_of_bedrooms: 6,
    type: "Estate",
  },
  {
    name: "Skyrise Penthouse",
    description: "Luxurious penthouse with panoramic views from the skyscraper",
    city: "Skyline City",
    no_of_bedrooms: 4,
    type: "Penthouse",
  },
  {
    name: "Riverside Townhouse",
    description: "Modern townhouse with river views and contemporary design",
    city: "Riverside Town",
    no_of_bedrooms: 3,
    type: "Townhouse",
  },
  {
    name: "Historic Mansion",
    description: "Grand mansion with rich history and opulent interiors",
    city: "Historic District",
    no_of_bedrooms: 8,
    type: "Mansion",
  },
];
